name: Linting

on:
  workflow_dispatch

jobs:
  dependencyAnalysis:
    name: Dependency Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV

      - name: Project Health
        run: git clone -b kartikaya.test https://github.com/staktrace/dependency-analysis-gradle-plugin ../dependency-analysis-gradle-plugin && gradle :misk-proto:projectHealth
